# Generated by Django 6.0.6 on 2026-07-01 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(blank=True, max_length=63, null=True, unique=True),
        ),
    ]
